services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    container_name: rentx
    ports:
      - "3333:3333"
    env_file:
      - .env
    command: pnpm start
    volumes:
      - .:/usr/app # Mapeia o diretório local para o contêiner
      - /usr/app/node_modules # Evita conflitos de node_modules entre host e contêiner
    depends_on:
      - database_ignite # Garante que o banco de dados esteja iniciado antes do app
    environment:
      - DATABASE_HOST=database_ignite # Adicione esta variável para facilitar a configuração

volumes:
  pgdata:
    driver: local
