services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    container_name: rentx
    ports:
      - "3333:3333"
    env_file:
      - .env
    command: pnpm start

volumes:
  pgdata:
    driver: local
